// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"database/sql"
	"frete-rapido-api/pkg/shipping"
)

// Injectors from wire.go:

func Build(db *sql.DB) shipping.Handler {
	shippingHandler := Must()
	return shippingHandler
}
