// Code generated by mockery v2.38.0. DO NOT EDIT.

package repository

import (
	shipping "frete-rapido-api/pkg/shipping"

	mock "github.com/stretchr/testify/mock"
)

// Mock is an autogenerated mock type for the Repository type
type Mock struct {
	mock.Mock
}

// Create provides a mock function with given fields: carrier
func (_m *Mock) Create(carrier *shipping.CarrierInfo) error {
	ret := _m.Called(carrier)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*shipping.CarrierInfo) error); ok {
		r0 = rf(carrier)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMock creates a new instance of Mock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock {
	mock := &Mock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
