definitions:
  handler.AddressDoc:
    properties:
      country:
        example: BRA
        type: string
      type:
        example: 0
        type: integer
      zipcode:
        example: 1324553
        type: integer
    type: object
  handler.Carrier:
    properties:
      deadline:
        example: "3"
        type: string
      name:
        example: Expresso FR
        type: string
      price:
        example: 17
        type: integer
      service:
        example: Normal
        type: string
    type: object
  handler.CarrierMetricsDoc:
    properties:
      average_price:
        example: 18.5
        type: number
      results:
        example: 3
        type: integer
      total:
        example: 55.5
        type: number
    type: object
  handler.DispatchersDoc:
    properties:
      registered_number:
        example: "12345"
        type: string
      volumes:
        items:
          $ref: '#/definitions/handler.Volume'
        type: array
      zipcode:
        example: 1324553
        type: integer
    type: object
  handler.MetricsResposneDoc:
    properties:
      carriers:
        additionalProperties:
          $ref: '#/definitions/handler.CarrierMetricsDoc'
        type: object
      higher_price:
        example: 55.5
        type: number
      lowest_price:
        example: 15.5
        type: number
    type: object
  handler.QuotesResponseDoc:
    properties:
      carriers:
        items:
          $ref: '#/definitions/handler.Carrier'
        type: array
    type: object
  handler.ShipperDoc:
    properties:
      category:
        example: 0ScdOLqC3r
        type: string
      registered_number:
        example: "12345"
        type: string
      token:
        example: 19ebbe852f2f48be9713e802522783ee
        type: string
    type: object
  handler.ShippingDataDoc:
    properties:
      dispatchers:
        items:
          $ref: '#/definitions/handler.DispatchersDoc'
        type: array
      recipient:
        $ref: '#/definitions/handler.AddressDoc'
      shipper:
        $ref: '#/definitions/handler.ShipperDoc'
      simulation_type:
        items:
          type: integer
        type: array
    type: object
  handler.Volume:
    properties:
      amount:
        example: 1
        type: integer
      category:
        example: "7"
        type: string
      height:
        example: 0.2
        type: number
      length:
        example: 0.2
        type: number
      price:
        example: 350
        type: integer
      unitary_price:
        example: 5.2
        type: number
      unitary_weight:
        example: 5.2
        type: number
      width:
        example: 0.2
        type: number
    type: object
info:
  contact:
    name: Leonardo Bispo
  description: Frete Rápido challenge to develop Rest API for external queries and
    return only expected values.
  title: Frete Rápido back-end challenge
  version: "1.0"
paths:
  /metrics:
    get:
      description: Endpoint to search quotes data in database
      parameters:
      - description: Informs the number of quotes that will be returned
        in: query
        name: last_quotes
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.MetricsResposneDoc'
      summary: Get quotes data in database
      tags:
      - shipping
  /quotes:
    post:
      consumes:
      - application/json
      description: Endpoint to fetch quotes data from the Frete rápido API and persists
        it in the database
      parameters:
      - description: body request
        in: body
        name: shippingData
        required: true
        schema:
          $ref: '#/definitions/handler.ShippingDataDoc'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.QuotesResponseDoc'
      summary: Fetch quote data and persist in database
      tags:
      - shipping
swagger: "2.0"
